### ISSUE TITLE
一个小问题，请指教

### ISSUE THREAD

**Issue by RYFan-RS** [mengxiaoxu/economic_audit_knowledge_graph#1]
请问一下你的流程图里面那个从文本分类模型到领域词库是如何做到的，另外就是如何从互动百科“获取领域词条信息10w个”，这里是将爬的文章分词再丢到互动百科去看有没有吗？如果是这样的话，如果分词不准该怎么办呢？谢谢指教。

**Comment by Guanngxu** [comment]
我是把百科词条的解释直接放到文本分类模型中的，如果这段文本属于领域文本，那就认为这个词条属于领域词汇。（百科类网站刚好提供了词条和词条的解释）

**Comment by RYFan-RS** [comment]
o  明白了 谢谢解答

**Comment by WSNuser** [comment]
您好，同样请教一下，1、百度百科和互动百科的爬虫是去农业知识图谱的链接找吗？ 2、这个文本分类模型具体如何构建？   小白问题比较多，多谢了

**Comment by Guanngxu** [comment]
第一个问题没有看明白，抱歉！
第二个，用机器学习算法自己搭建文本分类模型。

**Comment by WSNuser** [comment]
第一个问题是 我在你的流程图上看到有百度百科和互动百科的爬虫，但是没有找到相应的程序，在你给的华东师大农业知识图谱的链接里，只看到互动百科的爬虫demo，没有找到百科百科的爬虫~

**Comment by Guanngxu** [comment]
百度百科爬虫是我自己写的，和农业知识图谱里面的爬虫类似

**Comment by WSNuser** [comment]
你好，最近我把你的例程跑起来试了一下，启动web服务后，同时也链接了neo4j，但是在进行实体查询（该实体已确认存在neo4j种）的时候，每次都直接弹出 “数据库中暂时未录入该实体“的提示，或者直接出现404的页面，请假一下原因。谢谢

![tim 20180822170147](https://user-images.githubusercontent.com/10933314/44454263-a06c6e80-a62d-11e8-910d-32a155f195f0.png)

**Comment by shenliyan01** [comment]
非常感谢你的分享，我目前做的是水稻高产栽培模式知识图谱，目前我基于那个华东师范大学的基础之上已经基本完成了，目前就是有一个小问题，我搞了好久都没有完成，就是那个展示的部分，就是那个康德到辩护人等有好几个节点关联在一起的那个，不知道如何展示。求指点以下，我也关注了你的微信号，

**Comment by shenjichenai** [comment]
请问有码云版本的吗，是在是git上下载太慢了些
